server {
    listen       8080;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location /token {
        proxy_pass http://security:3000/v1/token;
    }

    location = /token/validation {
        proxy_pass http://security:3000/v1/token/validation;
    }

    location /upload {
        auth_request /token/validation;
        proxy_pass http://uploader:3000/v1/upload;
    }

    location /images {
        proxy_pass http://storage:9000/data/;
    }

}
